{
 "title": "Dashboard",
 "time": { "from": "2025-06-24T12:27:30.719Z", "to": "2025-08-23T12:27:30.719Z" },
 "panels": [
  {
   "title": "Pedidos finalizados",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT DATE(created_at) AS time, SUM(totalAmount) AS value\nFROM orders\nWHERE status = 'COMPLETED'\nGROUP BY DATE(created_at)\n"
    }
   ]
  },
  {
   "title": "Pedidos realizados em cada endereço",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\n  CONCAT(a.street, ' ', a.number, ' - ', a.city) AS location,\n  a.latitude,\n  a.longitude,\n  COUNT(o.id) AS order_count\nFROM addresses a\nJOIN orders o ON o.address_id = a.id\nWHERE a.latitude IS NOT NULL AND a.longitude IS NOT NULL\nGROUP BY a.id, a.street, a.number, a.city, a.latitude, a.longitude\n"
    }
   ]
  },
  {
   "title": "Total de pedidos por status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT status AS metric, COUNT(*) AS value\nFROM orders\nGROUP BY status\n"
    }
   ]
  },
  {
   "title": "Produtos mais vendidos",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT products.name AS metric, SUM(order_items.quantity) AS value\nFROM order_items\nJOIN products ON products.id = order_items.product_id\nGROUP BY products.name\nORDER BY value DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Número de itens nos carrinhos por usuário",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT users.name AS metric, \n  SUM(cart_items.quantity) AS quantity,\n  SUM(cart_items.unitPrice * cart_items.quantity) AS total_value\nFROM cart_items\nJOIN carts ON carts.id = cart_items.cart_id\nJOIN users ON users.id = carts.user_id\nGROUP BY users.name\n"
    }
   ]
  },
  {
   "title": "Quantidade de produtos por categoria",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT categories.name AS metric, COUNT(*) AS value\nFROM products\nJOIN categories ON products.category_id = categories.id\nGROUP BY categories.name"
    }
   ]
  }
 ]
}